### ISSUE TITLE
How can i use this for android ???

### ISSUE THREAD

**Issue by maravilhosinga** [felix-dumit/PFUser-Digits#26]
Hi, this is working very well in my iOS app, but i still not able to login this in android.

Can you please give me idea of how to use this in android, even the method to call example, becomeInBackroud to get user session or other thing ???

Help please.

**Comment by felix-dumit** [comment]
You should be able to call the equivalent method for android. 
I'm not using the `becomeInBackground` anymore. Now everything is done through `PFUser.authenticateWith(type: 'digits', authData: data)`. (It needs to have set a delegate for the 'digits' auth type.)

**Comment by maravilhosinga** [comment]
Do you have any dumentation for this type of authetication ?? or just a link where they explain this ?it may help

**Comment by felix-dumit** [comment]
There doesn't seem to be much documentation for this. Only the api reference: https://parseplatform.github.io/Parse-SDK-Android/api/com/parse/ParseUser.html#logInWithInBackground(java.lang.String,%20java.util.Map)

I recommend looking through that and the source code for this library, since you'll pretty much have to call the same methods with the same parameters.

**Comment by maravilhosinga** [comment]
Thank you! I'm working on the solution then if its works i will make a pull request here

**Comment by felix-dumit** [comment]
That'd be great, thanks!
